const data = {
    products: [
      {
        _id: '1',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/img3.jpg',
        price: 120,
        brand: 'GGC',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/img3.jpg',
        price: 120,
        brand: 'GGC',
        countInStock: 7,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/img2.jpg',
        price: 120,
        brand: 'GGC',
        countInStock: 9,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/img1.jpg',
        price: 120,
        brand: 'GGC',
        countInStock: 2,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canaste.jpeg',
        price: 120,
        brand: 'GGC',
        countInStock: 4,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;