const data = {
    products: [
      {
        _id: '1',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Canasta',
        category: 'Canasta',
        image: '/images/canasta.jpg',
        price: 120,
        brand: 'GGC',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;